In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Bernoulli naive Bayes

Run the below cell to get the following variables:

`X` = Data matrix of shape $(n, d)$. All the features are binary taking values $0$ or $1$.

`y` = label vector. Labels are $0$ and $1$.

In [ ]:
rng = np.random.default_rng(seed=1)
X1 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.7), rng.binomial(size = 50,n = 1, p =0.2))).reshape(-1, 1)
X2 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.6), rng.binomial(size = 50,n = 1, p =0.1))).reshape(-1, 1)
X3 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.6), rng.binomial(size = 50,n = 1, p =0.2))).reshape(-1, 1)
X4 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.8), rng.binomial(size = 50,n = 1, p =0.1))).reshape(-1, 1)


X = np.column_stack((X1,X2,X3,X4))

y = np.concatenate((np.zeros(50, dtype= int), np.ones(50, dtype = int))).reshape(-1, 1)
permute = rng.permuted(range(100))

X = X[permute]
y = y[permute]


In [ ]:
a=np.array([1,2,3,4,5])
p=rng.permuted(range(5))
print(p)
a[p]

[2 4 0 1 3]


array([3, 5, 1, 2, 4])

## Question 1
If we train the naive Bayes model on the dataset, What will be the value of $\hat{p}$, the estimate for $P(Y=1)$?



In [ ]:
# Enter your solution here
# p_hat -> fraction of one
# boolean indexing
y[y[:,0]==1].shape[0]/y.shape[0]

0.5

In [ ]:
y[:,0]

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0])

In [ ]:
def pij(f,l): # f->feature, l=label | to find P(feature f=1|Y=l)
  ind=y[:,0]==l #index-label condition
  labels=y[ind]
  col=X[ind,f] #feature f, index->ind boolean
  cond=col==1 #feature condition
  return col[cond].sum()/col.shape[0]

## Question 2
What will be the value of $\hat{p}_0^0$, the estimate of $P(f_0=1|y=0)$?  Write your answer correct to two decimal places.



In [ ]:
# Enter your solution here
#count(all data points with label ==0 and with feature 0 ==1/count(all labels==0)
pij(0,0)

0.68

## Question 3
What will be the value of $\hat{p}_0^1$, the estimate of $P(f_0=1|y=1)$?  Write your answer correct to two decimal places.



In [ ]:
# Enter your solution here
pij(0,1)

0.26

## Question 4
What will be the value of $\hat{p}_3^1$, the estimate of $P(f_3=1|y=1)$?  Write your answer correct to two decimal places.




In [ ]:
# Enter your solution here
pij(3,1)

0.12

In [ ]:
np.zeros(shape=(2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
def predict(test):
  d=len(test) # no. of features
  p=0.5
  P=np.zeros(shape=(2,4))
  for i in range(2): # labels
    for j in range(4): # features
      P[i,j]=pij(j,i)

  #P(y=1|test)
  p1=(p)
  for f in range(d):
    p1=p1*((P[1,f])**test[f])*((1-P[1,f])**(1-test[f]))
  #P(y=0|test)
  p2=(1-p)
  for f in range(d):
    p2=p2*((P[0,f])**test[f])*((1-P[0,f])**(1-test[f]))
  #condition
  if(p1>p2):
    return 1
  else:
    return 0

## Question 5

What will be the predicted label for the point $[1, 0, 1, 0]$?



In [ ]:
# Enter your solution here
predict(np.array([1,0,1,0]))

1

## Question 6

What will be the predicted label for the point $[1, 0, 1, 1]$?



In [ ]:
# Enter your solution here
predict(np.array([1,0,1,1]))

0

# Gaussian naive Bayes

Run the below cell to get the following variables:

`X_train` = Training dataset of the shape $(n, d)$. All the examples are coming from multivariate gaussian distribution.

`y_train` = label vector for corresponding training examples. labels are $0$ and $1$.

`X_test` = Test dataset of the shape $(m, d)$, where $m$ is the number of examples in the test dataset. All the examples are coming from multivariate gaussian distribution.

`y_test` = label vector for corresponding test examples. labels are $0$ and $1$.



In [ ]:
from sklearn.datasets import make_classification, make_blobs
from sklearn.model_selection import train_test_split

# generate artificial data points
X, y = make_blobs(n_samples = 100,
                  n_features=2,
                  centers=[[5,5],[10,10]],
                  cluster_std=1.5,
                  random_state=2)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    random_state=123)

## Question 7

How many examples are there in the trianing dataset?



In [ ]:
# Enter your solution here
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((80, 2), (20, 2), (80,), (20,))

## Question 8
How many features are there in the dataset?



In [ ]:
# Enter your solution here
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((80, 2), (20, 2), (80,), (20,))

## Question 9

If we train the Gaussian naive Bayes model on the trianing dataset, What will be the value of $\hat{p}$, the estimate for $P(Y=1)$? Write your answer correct to two decimal places.





In [ ]:
# Enter your solution here
y_train[y_train==1].sum()/y_train.shape[0]

0.4875

In [ ]:
y_train[y_train==1].sum()

39

## Question 10

If $\hat{\mu}_0 = [\mu_1, \mu_2, ..., \mu_d]$ be the estimate for $\mu_0$, the mean of $0$ labeled examples, what will be the value of $\mu_1+\mu_2+...+\mu_d$? Write your answer correct to two decimal places.



In [ ]:
# Enter your solution here
m0=X_train[y_train==0,:].mean(axis=0)
m0

array([4.55853975, 5.01739665])

In [ ]:
m0.sum()

9.575936394688135

In [ ]:
m1=X_train[y_train==1,:].mean(axis=0)
m1

array([10.30431548, 10.08580617])

We will be using the different covariances for different labeled examples. The estimate for $\Sigma_k$ will be

$$\hat{\Sigma}_k = \sigma_iI$$ where $\sigma_i$ is the variance of $i^{th}$ feature values of examples labeled $k$.



## Question 11
What will be value of $\text{trace}({\hat{\Sigma}}_0)$?  Write your answer correct to two decimal places.







In [ ]:
# Enter your solution here
# take all the training data points with labels as 0
# find covariance matrix here
# pick the variances
n=len(y_train[y_train==0])
data=X_train[y_train==0,:]
S=np.zeros(shape=(2,2))
for i in range(n):
  w=data[i]-m0
  S=S+w.reshape(2,1)@w.reshape(1,2)
S=(1/n)*S
S
v0=S[0,0]
v1=S[1,1]
v0+v1

4.435204194501573

In [ ]:
X_train[3].reshape(2,1)@X_train[3].reshape(1,2)

array([[115.49607933, 109.50839575],
       [109.50839575, 103.8311327 ]])

In [ ]:
n=80
S=np.zeros(shape=(2,2))
for i in range(n):
  l=y[i]
  if(l==0):
    w=X_train[i]-m0
  else:
    w=X_train[i]-m1
  S=S+w.reshape(2,1)@w.reshape(1,2)
S=(1/n)*S
S

array([[14.32319537, 10.11430522],
       [10.11430522, 11.42687251]])

In [ ]:
def pred(x,m0=m0,m1=m1,S=S):
  p=0.4875
  e=2.71828
  #P(y=1|x)
  p1=p
  power=(-0.5)*(x-m1).reshape(1,2)@S@(x-m1).reshape(2,1)
  p1=p1*(e**power)
  #P(y=0|x)
  p0=1-p
  power=(-0.5)*(x-m0).reshape(1,2)@S@(x-m0).reshape(2,1)
  p0=p0*(e**power)
  #predict
  if(p1>=p0):
    return 1
  else:
    return 0

## Question 12

Once we have estimated all the parameters for Gaussian naive Bayes assuming the different covariance matrices, we predict the labels for the training examples. What will be the training accuracy?

Accuracy is defined as the proportion of correctly classified examples.  Write your answer correct to two decimal places.




In [ ]:
# Enter your solution here
train_pred=[]
for i in range(80):
  v=X_train[i]
  train_pred.append(pred(v))

In [ ]:
[train_pred==y_train]

[array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])]

## Question 13

What will be the test accuracy?

Accuracy is defined as the proportion of correctly classified examples.  




In [ ]:
# Enter your solution here
test_pred=[]
for i in range(20):
  v=X_test[i]
  test_pred.append(pred(v))

In [ ]:
test_pred==y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])